// Nomes oficiais dos comandos padronizados com o prefixo py-*
module.exports = {
  PING: 'py-ping',
  STATUS: 'py-status',
  HELP: 'py-ajuda',
  WELCOME: 'py-boasvindas',
  SIXSEVEN: 'py-sixseven',
  SHIP: 'py-casal',
  DAILY: 'py-diario',
  WALLET: 'py-carteira',
  PROFILE: 'py-perfil',
  MARRIAGE: 'py-casamento',
  DIVORCE: 'py-divorcio',
  RANKING: 'py-ranking',
  ECONOMY_CONFIG: 'py-configeconomia',
  SET_ECONOMY: 'py-setareconomia',
  RESET_ECONOMY: 'py-resetareconomia',
  PROFESSION: 'py-profissao',
  WORK: 'py-trabalho',
  PET_EXPLORE: 'py-explorar',
  PYMONS: 'py-pymons',
  PIXELMONSTERS: 'py-pymons',
  PET: 'py-pymons',
  PET_DUEL: 'py-duelo',
  SHOP: 'py-loja',
  BUY: 'py-comprar',
  SELL: 'py-vender',
  INVENTORY: 'py-inventario',
  USE: 'py-usar',
  AGENDA: 'py-agenda',
  EMOJIS: 'py-emojis',
  DEX: 'py-dex',
  INVITE: 'py-convite',
  TRADE: 'py-trocar',
  EXPEDITION: 'py-expedicao',
  BOSS: 'py-boss',
  TAROT: 'py-tarot',
};
