// Nomes oficiais dos comandos. Altere aqui para atualizar slash e prefixo.
module.exports = {
  PING: 'ping',
  STATUS: 'status',
  HELP: 'ajuda',
  PREFIX: 'prefixo',
  WELCOME: 'boasvindas',
  SIXSEVEN: 'sixseven',
  SHIP: 'casal',
  DAILY: 'diario',
  WALLET: 'carteira',
  PROFILE: 'perfil',
  MARRIAGE: 'casamento',
  DIVORCE: 'divorcio',
  RANKING: 'ranking',
  ECONOMY_CONFIG: 'configeconomia',
  SET_ECONOMY: 'setareconomia',
  RESET_ECONOMY: 'resetareconomia',
  PROFESSION: 'profissao',
  WORK: 'trabalho',
  ADOPTION: 'adocao',
  PET_EXPLORE: 'petexplorar',
};
